import { images } from "@/constants";
import icons from "../constants/icons";

export const DUMMY_CHAT = [
  {
    id: "1",
    pfp: images.mashGroup,
    name: "Alice Johnson",
    userName: "alice_j",
    icon: icons.gallery,
    message: "I want to trade $100.00 Amazon...",
    timestamp: "1:00 PM",
    status: "PENDING", // UNANSWERED, PENDING, COMPLETED, DECLINED
    seen: false,
    online: true,
    group: false,
  },
  {
    id: "2",
    pfp: images.mashGroup,
    name: "Michael Smith",
    userName: "michael_s",
    icon: icons.gallery,
    message: "Can I get more details about your services?",
    timestamp: "1:15 PM",
    status: "UNANSWERED",
    seen: false,
    online: false,
    group: false,
  },
  {
    id: "3",
    pfp: images.mashGroup,
    name: "Emma Brown",
    userName: "emma_b",
    icon: icons.gallery,
    message: "When will I receive my payment?",
    timestamp: "1:30 PM",
    status: "COMPLETED",
    seen: true,
    online: true,
    group: false,
  },
  {
    id: "4",
    pfp: images.mashGroup,
    name: "Liam Wilson",
    userName: "liam_w",
    icon: icons.gallery,
    message: "Please call me back regarding the offer.",
    timestamp: "2:00 PM",
    status: "DECLINED",
    seen: false,
    online: true,
    group: false,
  },
  {
    id: "5",
    pfp: images.mashGroup,
    name: "Sophia Davis",
    userName: "sophia_d",
    icon: icons.gallery,
    message: "I sent an email with my inquiry.",
    timestamp: "2:30 PM",
    status: "PENDING",
    seen: true,
    online: true,
    group: false,
  },
  {
    id: "6",
    pfp: images.mashGroup,
    name: "James Miller",
    userName: "james_m",
    icon: icons.gallery,
    message: "I want to trade $50.00 PayPal.",
    timestamp: "3:00 PM",
    status: "PENDING",
    seen: false,
    online: true,
    group: false,
  },
  {
    id: "7",
    pfp: images.mashGroup,
    name: "Isabella Martinez",
    userName: "isabella_m",
    icon: icons.gallery,
    message: "Thanks for completing my request!",
    timestamp: "3:30 PM",
    status: "COMPLETED",
    seen: true,
    online: true,
    group: false,
  },
  {
    id: "8",
    pfp: images.mashGroup,
    name: "William Anderson",
    userName: "william_a",
    icon: icons.gallery,
    message: "There seems to be an issue with my order.",
    timestamp: "4:00 PM",
    status: "UNANSWERED",
    seen: false,
    online: true,
    group: false,
  },
  {
    id: "9",
    pfp: images.mashGroup,
    name: "Mia Thomas",
    userName: "mia_t",
    icon: icons.gallery,
    message: "I want to trade $200.00 eBay...",
    timestamp: "4:30 PM",
    status: "PENDING",
    seen: true,
    online: true,
    group: false,
  },
  {
    id: "10",
    pfp: images.mashGroup,
    name: "Benjamin Jackson",
    userName: "benjamin_j",
    icon: icons.gallery,
    message: "Can you assist me with my request?",
    timestamp: "5:00 PM",
    status: "UNANSWERED",
    seen: false,
    online: true,
    group: false,
  },
];
