export const usersData = [
  {
    id: "1",
    name: "Qamardeen Malik",
    surname: "Malik",
    firstName: "Qamardeen",
    username: "Alucard",
    email: "qamardeen.malik@example.com",
    phoneNumber: "+12345678901",
    gender: "Male",
    password: "Password123!",
    referralCode: "REF12345",
    country: "USA",
    bvn: "BVN001",
    dateOfBirth: "1990-01-01",
    status: "Failed",
    updateStatus: "Pending",
    usernameTag: "@Alucard", // Added usernameTag with '@'
  },
  {
    id: "2",
    name: "Adam Sandler",
    surname: "Sandler",
    firstName: "Adam",
    username: "Adam",
    email: "adam.sandler@example.com",
    phoneNumber: "+12345678902",
    gender: "Male",
    password: "SecurePass456!",
    referralCode: "REF67890",
    country: "Canada",
    bvn: "BVN002",
    dateOfBirth: "1986-05-12",
    status: "Successful",
    updateStatus: "Successful",
    usernameTag: "@Adam",
  },
  {
    id: "3",
    name: "Sasha Sloan",
    surname: "Sloan",
    firstName: "Sasha",
    username: "Sasha",
    email: "sasha.sloan@example.com",
    phoneNumber: "+12345678903",
    gender: "Female",
    password: "Pass7890!",
    referralCode: "REF11223",
    country: "UK",
    bvn: "BVN003",
    dateOfBirth: "1992-07-23",
    status: "Successful",
    updateStatus: "Successful",
    usernameTag: "@Sasha", 
  },
  {
    id: "4",
    name: "John Doe",
    surname: "Doe",
    firstName: "John",
    username: "john",
    email: "john.doe@example.com",
    phoneNumber: "+12345678904",
    gender: "Male",
    password: "DoeSecure321!",
    referralCode: "REF44556",
    country: "Australia",
    bvn: "BVN004",
    dateOfBirth: "1988-03-17",
    status: "Failed",
    updateStatus: "Pending",
    usernameTag: "@john", // Added usernameTag with '@'
  },
  {
    id: "5",
    name: "Jane Smith",
    surname: "Smith",
    firstName: "Jane",
    username: "jane",
    email: "jane.smith@example.com",
    phoneNumber: "+12345678905",
    gender: "Female",
    password: "SmithPass852!",
    referralCode: "REF77889",
    country: "India",
    bvn: "BVN005",
    dateOfBirth: "1995-10-11",
    status: "Successful",
    updateStatus: "Successful",
    usernameTag: "@jane",
  },
  {
    id: "6",
    name: "Michael Clark",
    surname: "Clark",
    firstName: "Michael",
    username: "mike",
    email: "michael.clark@example.com",
    phoneNumber: "+12345678906",
    gender: "Male",
    password: "ClarkSecure159!",
    referralCode: "REF99001",
    country: "Germany",
    bvn: "BVN006",
    dateOfBirth: "1984-08-30",
    status: "Failed",
    updateStatus: "Pending",
    usernameTag: "@mike",
  },
  {
    id: "7",
    name: "Emily Davis",
    surname: "Davis",
    firstName: "Emily",
    username: "emily",
    email: "emily.davis@example.com",
    phoneNumber: "+12345678907",
    gender: "Female",
    password: "EmilyPass753!",
    referralCode: "REF22334",
    country: "France",
    bvn: "BVN007",
    dateOfBirth: "1997-06-05",
    status: "Successful",
    updateStatus: "Successful",
    usernameTag: "@emily", // Added usernameTag with '@'
  },
];

export const transactionsData = [
  {
    id: "1",
    name: "Razer Gold",
    status: "Completed",
    subTitle: "Adam",
    giftCardType: "Amazon Gift card",
    assignedAgent: "Umar Draz",
    email: "qamardeen.malik@12.com",
    category: "Team",
    giftCardSubType: "-",
    gender: "Male",
    code: "090f-1234",
    serviceType: "Gift Card",
    quantity: "2",
    transctionType: "Sell - BTC",
    amount: "$450",
    date: "Nov 5, 2024",
    joined: "Nov 5, 2024",
  },
  {
    id: "2",
    name: "Razer Gold",
    status: "Pending",
    subTitle: "Sarah",
    giftCardType: "Amazon Gift card",
    assignedAgent: "Ayesha Khan",
    email: "sarah.ali@12.com",
    category: "Team",
    giftCardSubType: "-",
    gender: "Female",
    code: "090f-5678",
    serviceType: "Gift Card",
    quantity: "1",
    transctionType: "Sell - ETH",
    amount: "$200",
    date: "Nov 7, 2024",
    joined: "Nov 7, 2024",
  },
  {
    id: "3",
    name: "Razer Gold",
    status: "Completed",
    subTitle: "James",
    giftCardType: "Google Play",
    assignedAgent: "Zara Iqbal",
    email: "james.smith@12.com",
    category: "Team",
    giftCardSubType: "-",
    gender: "Male",
    code: "090f-9101",
    serviceType: "Gift Card",
    quantity: "3",
    transctionType: "Sell - BTC",
    amount: "$720",
    date: "Nov 12, 2024",
    joined: "Nov 12, 2024",
  },
  {
    id: "4",
    name: "Razer Gold",
    status: "Failed",
    subTitle: "Emily",
    giftCardType: "Amazon Gift card",
    assignedAgent: "Sana Ali",
    email: "emily.johnson@12.com",
    category: "Team",
    giftCardSubType: "-",
    gender: "Female",
    code: "090f-1122",
    serviceType: "Gift Card",
    quantity: "5",
    transctionType: "Sell - LTC",
    amount: "$1000",
    date: "Nov 14, 2024",
    joined: "Nov 14, 2024",
  },
  {
    id: "5",
    name: "Razer Gold",
    status: "Completed",
    subTitle: "Michael",
    giftCardType: "Amazon Gift card",
    assignedAgent: "Ali Raza",
    email: "michael.brown@12.com",
    category: "Team",
    giftCardSubType: "-",
    gender: "Male",
    code: "090f-3344",
    serviceType: "Gift Card",
    quantity: "4",
    transctionType: "Sell - BTC",
    amount: "$350",
    date: "Nov 20, 2024",
    joined: "Nov 20, 2024",
  },
  {
    id: "6",
    name: "Razer Gold",
    status: "Pending",
    subTitle: "Daniel",
    giftCardType: "Google Play",
    assignedAgent: "Nadia Khan",
    email: "daniel.lee@12.com",
    category: "Team",
    giftCardSubType: "-",
    gender: "Male",
    code: "090f-5566",
    serviceType: "Gift Card",
    quantity: "6",
    transctionType: "Sell - ETH",
    amount: "$1500",
    date: "Nov 25, 2024",
    joined: "Nov 25, 2024",
  },
  {
    id: "7",
    name: "Razer Gold",
    status: "Completed",
    subTitle: "Jessica",
    giftCardType: "Amazon Gift card",
    assignedAgent: "Fariha Ahsan",
    email: "jessica.lee@12.com",
    category: "Team",
    giftCardSubType: "-",
    gender: "Female",
    code: "090f-7788",
    serviceType: "Gift Card",
    quantity: "3",
    transctionType: "Sell - BTC",
    amount: "$500",
    date: "Nov 28, 2024",
    joined: "Nov 28, 2024",
  },
];

export const transactionDetails = [
  {
    id: 1,
    amountDollar: "$250,000",
    amountNaira: "NGN425,000,000",
    serviceType: "Crypto Sell",
    cryptoType: "Bitcoin (BTC)",
    cryptoChain: "Bitcoin",
    cryptoAmount: "0.002 BTC",
    transactionId: "238Dsjfjfk3djmcdbsd",
    date: "Nov 6, 2024 - 11:22am",
    assignedAgent: "Qamardeen Abdulmalik",
    customer: "Sasha Sloan",
    transactionStatus: "Successful",
  },
  {
    id: 2,
    amountDollar: "$150,000",
    amountNaira: "NGN255,000,000",
    serviceType: "Crypto Buy",
    cryptoType: "Ethereum (ETH)",
    cryptoChain: "Ethereum",
    cryptoAmount: "0.5 ETH",
    transactionId: "3X8Y5jfjsk7kmcsdcd2",
    date: "Nov 7, 2024 - 2:45pm",
    assignedAgent: "Ahmed Yusuf",
    customer: "John Doe",
    transactionStatus: "Pending",
  },
  {
    id: 3,
    amountDollar: "$100,000",
    amountNaira: "NGN170,000,000",
    serviceType: "Crypto Sell",
    cryptoType: "Litecoin (LTC)",
    cryptoChain: "Litecoin",
    cryptoAmount: "1.2 LTC",
    transactionId: "459Lqwejdfnd7dkmsld",
    date: "Nov 8, 2024 - 9:30am",
    assignedAgent: "Aisha Bello",
    customer: "Jane Smith",
    transactionStatus: "Failed",
  },
  {
    id: 4,
    amountDollar: "$300,000",
    amountNaira: "NGN510,000,000",
    serviceType: "Crypto Buy",
    cryptoType: "Ripple (XRP)",
    cryptoChain: "Ripple",
    cryptoAmount: "1,000 XRP",
    transactionId: "76Fsjklsdm8asodsmkf",
    date: "Nov 9, 2024 - 4:00pm",
    assignedAgent: "Michael Olu",
    customer: "Chris Evans",
    transactionStatus: "Successful",
  },
  {
    id: 5,
    amountDollar: "$50,000",
    amountNaira: "NGN85,000,000",
    serviceType: "Crypto Sell",
    cryptoType: "Bitcoin (BTC)",
    cryptoChain: "Bitcoin",
    cryptoAmount: "0.001 BTC",
    transactionId: "9JLskdjhf84kjdsmclk",
    date: "Nov 10, 2024 - 10:15am",
    assignedAgent: "Fatima Alabi",
    customer: "Tony Stark",
    transactionStatus: "Pending",
  },
  {
    id: 6,
    amountDollar: "$75,000",
    amountNaira: "NGN127,500,000",
    serviceType: "Crypto Sell",
    cryptoType: "Ethereum (ETH)",
    cryptoChain: "Ethereum",
    cryptoAmount: "0.3 ETH",
    transactionId: "0ZSjdsmkdl3djfklsms",
    date: "Nov 11, 2024 - 6:20pm",
    assignedAgent: "Kola Johnson",
    customer: "Natasha Romanoff",
    transactionStatus: "Successful",
  },
  {
    id: 7,
    amountDollar: "$200,000",
    amountNaira: "NGN340,000,000",
    serviceType: "Crypto Buy",
    cryptoType: "Bitcoin (BTC)",
    cryptoChain: "Bitcoin",
    cryptoAmount: "0.01 BTC",
    transactionId: "1SDskldfn3dkjfkmcls",
    date: "Nov 12, 2024 - 8:50am",
    assignedAgent: "Adaobi Chukwu",
    customer: "Steve Rogers",
    transactionStatus: "Failed",
  },
];
